<div data-bind="scope: 'noiteContador'"><!-- ko template: getTemplate() --><!-- /ko --></div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "noiteContador": {
                    "component": "js/contador",
                    "dataFinal": "2026-11-01T00:00:00-03:00"
                }
            }
        }
    }
}
</script>
